### PR TITLE
feat: return gcp resources

### PR DESCRIPTION
**Pull request by donatas-dt**
# Description

Return gcp_resources in custom_train_job. Should allow to click "view custom job" in UI.
Relevant documentation: https://cloud.google.com/vertex-ai/docs/pipelines/build-own-components
image

# How has this been tested?

make e2e-tests
make test-all-components
Tests in CICD

# Checklist

- [X] I have commented my code, particularly in hard-to-understand areas
- [x] I have successfully run the E2E tests, and have included the links to the pipeline runs below
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [ ] I have updated any relevant documentation to reflect my changes
- [ ] I have assigned a reviewer and messaged them

# Pipeline run links:
https://console.cloud.google.com/vertex-ai/locations/europe-west2/pipelines/runs/tensorflow-prediction-pipeline-20230602085628?project=dt-turbo-templates-staging
https://console.cloud.google.com/vertex-ai/locations/europe-west2/pipelines/runs/xgboost-prediction-pipeline-20230602084746?project=dt-turbo-templates-staging
https://console.cloud.google.com/vertex-ai/locations/europe-west2/pipelines/runs/tensorflow-train-pipeline-20230602083603?project=dt-turbo-templates-staging
https://console.cloud.google.com/vertex-ai/locations/europe-west2/pipelines/runs/xgboost-train-pipeline-20230602083557?project=dt-turbo-templates-staging

### CODE REVIEW

**Comment by donatas-dt** [comment]
#19 Currently pipeline is failing: https://console.cloud.google.com/vertex-ai/locations/europe-west2/pipelines/runs/xgboost-train-pipeline-20230601100721?project=dt-turbo-templates-dev

**Comment by donatas-dt** [comment]
227fcbc
Pipeline run:
https://console.cloud.google.com/vertex-ai/locations/europe-west2/pipelines/runs/xgboost-train-pipeline-20230601112027?project=dt-turbo-templates-dev

**Review by felix-datatonic — APPROVED** [review]

**Review by ariadnafer — APPROVED** [review]

**Comment by ariadnafer** [comment]
lgtm!

**Pull request merged**
